core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    category_view,
    account_settings,
    getitems,
    validate_username,
)

app_name = 'core'

urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('', HomeView, name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('account_settings/', account_settings, name='account_settings'),

    path('category/<str:category>', category_view, name='category_view'),
    path('username/validation.', validate_username, name='validate_username'),
]

seller/urls.py
from django.views.generic import TemplateView
from django.urls import path
from .views import (
    # add_item,
    item_create,
    delete_item,
    update_item,
    # retailer_dash,
    # RetailerSignupView
    # send_push,
    admin,
    # mpesa,
    more_items,
    more_orders,
    BasicUploadView,
)

app_name = 'seller'

urlpatterns = [
    # path('add_item/', AddItemFormView.as_view(), name='add_item'),
    path('create_item/', item_create, name='add_item'),
    path('basic-upload/', BasicUploadView.as_view(), name='basic_upload'),
    path('update_item/<slug>', update_item, name='update_item'),
    path('delete_item/<slug>', delete_item, name='delete_item'),
    path('template/', admin, name='admin_view'),
    # path('mpesa/', mpesa),
    path('items/', more_items, name='items'),
    path('orders/', more_orders, name='orders'),
]

core/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.validators import RegexValidator
from django.db import models
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from django.utils import timezone
from allauth.account.models import EmailAddress
from django_countries.fields import CountryField

import random
import string


# CATEGORY_CHOICES = (
#     ('S', 'Shirt'),
#     ('SW', 'Sport wear'),
#     ('OW', 'Outwear')
# )

def randomslug():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


def photo_directory_path(instance, filename):
    """file will be saved to MEDIA_ROOT/photos/2018/01/2"""
    return 'photos/%Y/%m/%d/'


CATEGORY_CHOICES = (

    ('Laptops', 'Laptops'),
    ('Smartphones', 'Smartphones'),
    ('Tablets', 'Tablets'),
    ('Headphones', 'Headphones'),
    ('Camera', 'Camera'),
    ('Accesories', 'Accesories'),
    ('Tv', 'Tv'),
)

LABEL_CHOICES = (
    ('new', 'new'),
    ('best rated', 'best rated'),
    ('best seller', 'best seller')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


# class EcommerceUser(AbstractUser):
# is_retailer = models.BooleanField(default=False)

# created = models.DateTimeField(auto_now_add=True)
# modified = models.DateTimeField(auto_now=True)


class LoggedInUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='logged_in_user')
    session_key = models.CharField(max_length=32)

    def __str__(self):
        return self.user.username


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    is_retailer = models.BooleanField(default=False)
    company_name = models.CharField(max_length=50, null=True, blank=True)

    def add_email_address(self, request, new_email):
        # Add a new email address for the user, and send email confirmation.
        # Old email will remain the primary until the new one is confirmed.
        return EmailAddress.objects.add_email(request, self.user, new_email, confirm=True)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(choices=CATEGORY_CHOICES, max_length=50)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Label(models.Model):
    name = models.CharField(choices=LABEL_CHOICES, max_length=50)

    def __str__(self):
        return self.name


class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ManyToManyField('Category', related_name='items')
    label = models.ManyToManyField('Label', related_name='items')
    slug = models.SlugField(null=False, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to=photo_directory_path, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(null=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    def no_of_ratings(self):
        ratings = Rating.objects.filter(item=self)
        return len(ratings)

    def avg_rating(self):
        sum_of_ratings = 0
        ratings = Rating.objects.filter(item=self)
        for rating in ratings:
            sum_of_ratings += rating.rate
        if len(ratings) > 0:
            return sum_of_ratings / len(ratings)
        else:
            return 0

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=photo_directory_path)

    def __str__(self):
        return self.item.title


class Rating(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='review')
    # name = models.CharField(max_length=80)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # validators=[MinValueValidator(1), MaxValueValidator(5)]
    rate = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], null=True)
    subject = models.CharField(max_length=50, blank=True)
    review = models.TextField()
    # ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=False)
    created_on = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_on']

    def review_posted_when(self):
        now = timezone.now()
        duration = now - self.created_on
        seconds = duration.total_seconds()
        minutes = int((seconds % 3600) // 60)
        hours = int(seconds // 3600)

        if hours > 24:
            return f"{duration.days} days ago"
        elif hours < 24:
            if seconds > 60:
                if hours > 0:
                    return f"{hours} hrs {minutes} mins ago"
                else:
                    return f"{minutes} mins ago"
            elif seconds < 60:
                return "just now"

    def __str__(self):
        return 'Comment on  {} by {}'.format(self.subject, self.user)


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    phone_regex = RegexValidator(regex=r'^(?:254|\+254|0)?(7(?:[129][0-9])|(?:0[0-9]))[0-9]{6})$',
                                 message="phone number must be entered in the format:'+2547*******'")
    phone_number = models.CharField(validators=[phone_regex], max_length=14, blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()

templates/category_view.html
{% extends "base.html" %}

{% block content %}

<br>
    <main class="mt-5 pt-4">
        <div class="container">

          <div class="row pt-4">

            <!-- Content -->
            <div class="col-lg-12">

        <!-- Section small products -->

                <section>

                    <!-- Grid row -->
                    <div class="row">
                        <h1><strong>{{ category | title }}</strong></h1>
                            <!-- Grid column -->
                            <div class="col-12">
                                     <!-- Grid row -->
                                      <div class="row">
                                         {% for item in items %}
                                        <!-- Grid column -->
                                        <div class="col-lg-6 col-md-6 mb-4">

                                          <!-- Card -->
                                          <div class="card card-ecommerce">

                                            <!-- Grid row -->
                                            <div class="row">

                                              <!-- Grid column -->
                                              <div class="col-6 d-flex align-items-center">

                                                <!-- Card image -->
                                                <div class="view overlay">

                                                    <img src="{{ item.image.url }}"
                                                    class="img-fluid" alt="">

                                                  <a href="{{ item.get_absolute_url }}" >

                                                    <div class="mask rgba-white-slight"></div>

                                                  </a>

                                                </div>

                                                <!-- Card image -->
                                              </div>

                                              <!-- Grid column -->
                                              <div class="col-6 pl-0">

                                                <!-- Card content -->
                                                <div class="card-body">

                                                  <!-- Category & Title -->
                                            <h5 class="card-title mb-1"><strong><a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a></strong>
                                              <br>
                                              <small>
                                                  Categories:&nbsp;
                                                  {% for categor in item.category.all %}
                                                  <a href="{% url 'core:category_view' categor.name %}">
                                                      {{ categor.name }}
                                                  </a>&nbsp;
                                                  {% endfor %}
                                              </small>
                                               <br>
                                            </h5>
                                            {% for labe in item.label.all %}
                                                {% if labe.name == "best seller" %}
                                                  <span class="badge badge-danger mb-2">{{ labe.name }}</span>
                                                {% endif %}
                                                {% if labe.name == "new" %}
                                                  <span class="badge badge-info mb-2">{{labe.name}}</span>
                                                {% endif %}
                                                {% if labe.name == "best rated" %}
                                                  <span class="badge badge-success mb-2">{{labe.name}}</span>
                                                {% endif %}
                                            {% endfor %}

                                            <!-- Rating -->
                                            <ul class="rating">

                                              <li><i class="fas fa-star {% if item.avg_rating < 1 %}grey-text{% endif %}"></i></li>
                                              <li><i class="fas fa-star {% if item.avg_rating < 2 %}grey-text{% endif %}"></i></li>
                                              <li><i class="fas fa-star {% if item.avg_rating < 3 %}grey-text{% endif %}"></i></li>
                                              <li><i class="fas fa-star {% if item.avg_rating < 4 %}grey-text{% endif %}"></i></li>
                                              <li><i class="fas fa-star {% if item.avg_rating < 5 %}grey-text{% endif %}"></i></li>

                                            </ul>

                                                  <!-- Card footer -->
                                                  <div class="card-footer pb-0">

                                                    <div class="row mb-0">

                                                      <span class="float-left">
                                                        <strong>
                                                        {% if item.discount_price %}
                                                        <span class="mr-1">
                                                          <del style="color: red;">${{ item.price }}</del>
                                                        </span>
                                                        <span>${{ item.discount_price }}</span>
                                                        {% else %}
                                                        <span>${{ item.price }}</span>
                                                        {% endif %}
                                                      </strong></span>


                                                      <span class="float-right">

                                                        <a class="" data-toggle="tooltip" data-placement="top" title="Add to Cart"><i
                                                            class="fas fa-shopping-cart ml-3"></i></a>

                                                      </span>

                                                    </div>

                                                  </div>

                                                </div>
                                                <!-- Card content -->

                                              </div>

                                            </div>

                                          </div>
                                          <!-- Card -->

                                        </div>
                                        <!-- Grid column -->
                                        {% endfor %}
                                      </div>
                                      <!-- Grid row -->

                              </div>
                              <!-- Grid column -->


                    </div>
                    <!-- Grid row -->

                </section>
                <!-- Section small products -->
            </div>
          </div>
        </div>
    </main>


{% endblock content %}

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <!-- Main Layout -->
  <main>
    <!-- Main Container -->
    <div class="container">
            <!-- Shopping Cart table -->
            <div class="table-responsive text-nowrap">
                 <h2>Order Summary</h2>
              <table class="table">
                <!-- Table head -->
                <thead >
                  <tr>
                    <th class="font-weight-bold" scope="col">#</th>
                    <th class="font-weight-bold" scope="col">Item title</th>
                    <th class="font-weight-bold" scope="col">Price</th>
                    <th class="font-weight-bold" scope="col">Quantity</th>
                    <th class="font-weight-bold" scope="col">Total Item Price</th>
                      <th scope="col"></th>
                  </tr>
                </thead>
                <!-- Table head -->

                <!-- Table body -->
                <tbody>
                {% for order_item in object.items.all %}
                  <!-- Rows -->
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td>
                        
                        <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
                            <i class="fas fa-minus mr-2"></i>
                        </a>
                        <span class="qty">{{ order_item.quantity }}</span>
                        {% if order_item.quantity <= order_item.item.quantity|add:"-1" %}
                        <a href="{% url 'core:add-to-cart' order_item.item.slug %}">
                            <i class="fas fa-plus ml-2"></i>
                        </a>
                        {% endif %}

                    </td>

                    <td class="font-weight-bold">
                        {% if order_item.item.discount_price %}
                            ${{ order_item.get_total_discount_item_price }}
                            <span class="badge badge-success">Saving ${{ order_item.get_amount_saved }}</span>
                        {% else %}
                            ${{ order_item.get_total_item_price }}
                        {% endif %}
                    </td>

                      <td>
                        <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                            <button type="button" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top"
                            title="Remove item">X
                            </button>
                        </a>
                      </td>

                  </tr>
                  <!-- Rows -->

                {% empty %}
                <tr>
                    <td colspan='5'>Your cart is empty</td>
                </tr>
                <tr>
                    <td colspan="5">
                    <a class='btn btn-primary btn-rounded float-right' href="{% url 'core:home' %}">
                        <i class="fas fa-angle-left left"></i>Continue shopping</a>
                    </td>
                </tr>

                {% endfor %}

                {% if object.coupon %}
                <tr>
                    <td colspan="4"><b>Coupon</b></td>
                    <td><b>-${{ object.coupon.amount }}</b></td>
                </tr>
                {% endif %}

                {% if object.get_total %}
                 <!-- Total row -->
                  <tr>
                    <td colspan="4">
                      <h4 class="mt-2">
                        <strong>Total</strong>
                      </h4>
                    </td>

                    <td>
                      <h4 class="mt-2">
                        <strong>${{ object.get_total }}</strong>
                      </h4>
                    </td>
                  </tr>
                <!-- Total row -->

                  <tr>
                    <td colspan="8">
                        <a href="{% url 'core:checkout' %}">
                          <button type="button" class="btn btn-warning btn-rounded float-right ml-2">
                              PROCEED TO CHECKOUT
                              <i class="fas fa-angle-right right"></i>
                          </button>
                        </a>

                      <a href="{% url 'core:home' %}">
                          <button type="button" class="btn btn-primary btn-rounded float-right ">
                              <i class="fas fa-angle-left left"></i>
                              CONTINUE SHOPPING
                          </button>
                      </a>

                    </td>
                    {% endif %}
                  </tr>
                  <!-- Last row -->

                </tbody>
                  <!-- Table body -->
              </table>
            </div>
               <!-- Shopping Cart table -->
          </div>
  </main>
{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/retailer_dash.html
{% extends 'base.html' %}

{% block mega %}
{% include 'status.html' %}
<br>

<div class="btn-group">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Search Items Added</button>

    <div class="dropdown-menu">
         <form method="get">
             <span class="dropdown-item">Title: {{myfilter.form.title}}</span>
             <div class="dropdown-divider"></div>
             <span class="dropdown-item">Description: {{myfilter.form.description}}</span>
             <div class="dropdown-divider"></div>
             <span class="dropdown-item">Price: {{myfilter.form.price}}</span>
             <div class="dropdown-divider"></div>
             <span class="dropdown-item">Discount price: {{myfilter.form.discount_price}}</span>
             <div class="dropdown-divider"></div>
             <span class="dropdown-item">Label: {{myfilter.form.label}}</span>
             <div class="dropdown-divider"></div>
             <span class="dropdown-item">Category: {{myfilter.form.category}}</span>
             <div class="dropdown-divider"></div>
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
    </div>

</div>

<br>

<div  class="row">
        <div class="col-md">
            <h5>ITEMS ADDED</h5>
            <br>
            <div class="card card-body">

                <table class="table table-striped w-5">
                    <thead>
                         <tr>
                        <th>Item</th>
                         <th>Price</th>
                         <th>Discount Price</th>
                        <th>Category</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                    </thead>
                   <tbody>
                       {% for item in items %}
                    <tr>
                        <td>{{item.title}}</td>
                        <td>{{item.price}}</td>
                        <td>{{item.discount_price}}</td>
                        <td>{% for categor in item.category.all %}
                              {{ categor.name }}
                          {% endfor %}</td>
                        <td><a style="color:blue;" href="{% url 'seller:update_item' item.slug %}"><i class="fas fa-pen"></i></a></td>
                        <td><a style="color: red;" href="{% url 'seller:delete_item' item.slug %}"><i class="far fa-trash-alt float-right"></i></a></td>
                    </tr>
                    {% endfor %}
                   </tbody>
                    
                </table>
            </div>
        </div>
    </div>

<br>

    <div class="row">

        <div class="col-md-5">

         <div class="card card-body">
           <h5>Items</h5>
             <br>
             <a class="btn btn-outline-info btn-md btn-block" href="{% url 'seller:add_item' %}">Add Item</a>
         </div>
       </div>
    </div>

<br>

    <div class="row">
        <div class="col-md">
            <h5>LAST 5 ORDERS:</h5>
            <br>
            <div class="card card-body">
                <table class="table table-sm">
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                         <th>Date Ordered</th>
                         <th>Owner</th>
                        <th>Reference Code</th>
                    </tr>
                    
                    {% for order in orders %}
                    <tr>
                        <td>{% for order in order.items.all %}
                              {{ order.item.title }}
                          {% endfor %}</td>
                        <td>{% for order in order.items.all %}
                              {{ order.quantity }}
                          {% endfor %}</td>
                        <td>{{order.ordered_date}}</td>
                        <td>{{order.user}}</td>
                        <td>{{order.ref_code}}</td>
                    </tr>
                    {% endfor %}
                   
                </table>
            </div>
        </div>
    </div>

<br>



{% endblock mega %}
{% block extra_scripts %}
    
<script type="text/javascript" >
    $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
  {% endblock extra_scripts %}

templates/scripts.html
{% load static %}
  

<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/addons/steppers.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/addons/rating.js' %}"></script>




<!-- Initializations -->
<script type="text/javascript">
 $().ready(function () {

    setTimeout(function () {
      $('#ctn-preloader').addClass('loaded');
      // Una vez haya terminado el preloader aparezca el scroll
      $('body').removeClass('no-scroll-y');

      if ($('#ctn-preloader').hasClass('loaded')) {
        // Es para que una vez que se haya ido el preloader se elimine toda la seccion preloader
        $('#preloader').delay(1000).queue(function () {
          $(this).remove();
        });
      }
    }, 1000);

  });
  // Animations initialization
  new WOW().init();

  // Tooltips Initialization
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  // Material Select Initialization
  $(document).ready(function () {
    $('.mdb-select').materialSelect();
  });

  // SideNav Initialization
  $(".button-collapse").sideNav();

  window.setTimeout(function(){
    $(".alert").fadeTo(500, 0).slideUp(500,function(){
      $(this).remove();
    });
  },4000);

 

  
</script>