core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    category_view,
    account_settings,
    getitems,
    validate_username,
)

app_name = 'core'

urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('', HomeView, name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('account_settings/', account_settings, name='account_settings'),

    path('category/<str:category>', category_view, name='category_view'),
    path('username/validation.', validate_username, name='validate_username'),
]

seller/urls.py
from django.views.generic import TemplateView
from django.urls import path
from .views import (
    # add_item,
    item_create,
    delete_item,
    update_item,
    # retailer_dash,
    # RetailerSignupView
    # send_push,
    admin,
    # mpesa,
    more_items,
    more_orders,
    BasicUploadView,
)

app_name = 'seller'

urlpatterns = [
    # path('add_item/', AddItemFormView.as_view(), name='add_item'),
    path('create_item/', item_create, name='add_item'),
    path('basic-upload/', BasicUploadView.as_view(), name='basic_upload'),
    path('update_item/<slug>', update_item, name='update_item'),
    path('delete_item/<slug>', delete_item, name='delete_item'),
    path('template/', admin, name='admin_view'),
    # path('mpesa/', mpesa),
    path('items/', more_items, name='items'),
    path('orders/', more_orders, name='orders'),
]

templates/admin-dash/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Label - Premium Responsive Bootstrap 4 Admin & Dashboard Template</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/mdi/css/materialdesignicons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.addons.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- endinject -->
    <!-- vendor css for this page -->
    <!-- End vendor css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'assets/css/shared/style.css' %}">
    <!-- endinject -->
    <!-- Layout style -->
    <link rel="stylesheet" href="{% static 'assets/css/demo_1/style.css' %}">
    <!-- Layout style -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <!-- MDBootstrap Datatables  -->
    <link href="{% static 'css/addons/datatables.min.css' %}" rel="stylesheet">



    {% block extrastyle %}

    {% endblock extrastyle %}
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/toastr.min.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" />
  </head>
    <body class="header-fixed">
     
        <!-- partial:partials/_header.html -->

        {% include "admin-dash/navbar.html" %}
      <div class="page-body ">
      
        <!-- partial:partials/_sidebar.html -->
        <div class="sidebar">
          <div class="user-profile">
            <div class="display-avatar animated-avatar">
              <img class="profile-img img-lg rounded-circle" src="{% static 'assets/images/profile/male/image_1.png' %}"
                alt="profile image">
            </div>
            <div class="info-wrapper">
              <p class="user-name">{{request.user.first_name}} {{request.user.last_name}} </p>
              <h6 class="display-income">$3,400,00</h6>
            </div>
          </div>
          <ul class="navigation-menu">
            <li class="nav-category-divider">MAIN</li>
            <li>
              <a href="{% url 'seller:admin_view' %}">
                <span class="link-title">Dashboard</span>
                <i class="mdi mdi-gauge link-icon"></i>
              </a>
            </li>
            <li>
              <a href="#sample-pages" data-toggle="collapse" aria-expanded="false">
                <span class="link-title">Sample Pages</span>
                <i class="mdi mdi-flask link-icon"></i>
              </a>
              <ul class="collapse navigation-submenu" id="sample-pages">
                <li>
                  <a href="pages/sample-pages/login_1.html" target="_blank">Login</a>
                </li>
                <li>
                  <a href="pages/sample-pages/error_2.html" target="_blank">Error</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="#ui-elements" data-toggle="collapse" aria-expanded="false">
                <span class="link-title">UI Elements</span>
                <i class="mdi mdi-bullseye link-icon"></i>
              </a>
              <ul class="collapse navigation-submenu" id="ui-elements">
                <li>
                  <a href="pages/ui-components/buttons.html">Buttons</a>
                </li>
                <li>
                  <a href="{% url 'seller:items' %}">Tables</a>
                </li>
                <li>
                  <a href="pages/ui-components/typography.html">Typography</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="pages/forms/form-elements.html">
                <span class="link-title">Forms</span>
                <i class="mdi mdi-clipboard-outline link-icon"></i>
              </a>
            </li>
            <li>
              <a href="pages/charts/chartjs.html">
                <span class="link-title">Charts</span>
                <i class="mdi mdi-chart-donut link-icon"></i>
              </a>
            </li>
            <li>
              <a href="pages/icons/material-icons.html">
                <span class="link-title">Icons</span>
                <i class="mdi mdi-flower-tulip-outline link-icon"></i>
              </a>
            </li>
            <li class="nav-category-divider">DOCS</li>
            <li>
              <a href="../docs/docs.html">
                <span class="link-title">Documentation</span>
                <i class="mdi mdi-asterisk link-icon"></i>
              </a>
            </li>
          </ul>
          <div class="sidebar-upgrade-banner">
            <p class="text-gray">Upgrade to <b class="text-primary">PRO</b> for more exciting features</p>
            <a class="btn upgrade-btn" target="_blank" href="http://www.uxcandy.co/product/label-pro-admin-template/">Upgrade
              to PRO</a>
          </div>
        </div>
        {% block content %}

        {% endblock content %}
      </div>

    </body>
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% include "admin-dash/scripts.html" %}
    {% block javascript %}

    {% endblock javascript %}
</html>

templates/admin-dash/footer.html
<!-- partial:partials/_footer.html -->
        <footer class="footer">
          <div class="row">
            <div class="col-sm-6 text-center text-sm-right order-sm-1">
              <ul class="text-gray">
                <li><a href="#">Terms of use</a></li>
                <li><a href="#">Privacy Policy</a></li>
              </ul>
            </div>
            <div class="col-sm-6 text-center text-sm-left mt-3 mt-sm-0">
              <small class="text-muted d-block">Copyright © 2019  All rights reserved</small>
              <small class="text-gray mt-2">Handcrafted With <i class="mdi mdi-heart text-danger"></i></small>
            </div>
          </div>
        </footer>
        <!-- partial -->

templates/admin-dash/images.html
{% extends "admin-dash/base.html" %}
{% load static %}

{% block content %}
<div class="page-content-wrapper">
      <div class="page-content-wrapper-inner">
        <div class="content-viewport">
          <div class="row">
           {# 1. BUTTON TO TRIGGER THE ACTION #}
          <button type="button" class="btn btn-primary js-upload-photos">
            <span class="mdi mdi-cloud-upload"></span> Click to upload photos
          </button>
        <span>OR</span>
          {# 1. DROPZONE #}
          <div class="well text-muted text-center" style="padding-top: 4rem; padding-bottom: 4rem;">
            <span class="mdi mdi-arrow-down" style="font-size: 4rem;"></span>
            <h3>Drop Photos Here to Upload</h3>
          </div>

          {# 2. FILE INPUT TO BE USED BY THE PLUG-IN #}
          <input id="fileupload" type="file" name="file" multiple
                 style="display: none;"
                 data-url="{% url 'seller:basic_upload' %}"
                 data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

          {# 3. TABLE TO DISPLAY THE UPLOADED PHOTOS #}
          <table id="gallery" class="table table-bordered">
            <thead>
              <tr>
                <th>Photo</th>
              </tr>
            </thead>
            <tbody>
              {% for photo in photos %}
                <tr>
                  <td><a href="{{ photo.image.url }}">{{ photo.image.name }}</a></td>
                </tr>
              {% empty %}
                 <tr>
                  <td colspan="7" class="text-center bg-warning">No images yet</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
          {# MODAL TO DISPLAY UPLOAD PROGRESS #}
            <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title">Uploading...</h4>
                  </div>
                  <div class="modal-body">
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
  </div>

{% endblock content %}

{% block javascript %}
   {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'assets/js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'assets/js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'assets/js/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'assets/js/basic-upload.js' %}"></script>
{% endblock javascript%}

templates/admin-dash/items.html
{% extends "admin-dash/base.html" %}
{% load static %}
{% block extrastyle %}
<style type="text/css">
table.dataTable thead .sorting:after,
table.dataTable thead .sorting:before,
table.dataTable thead .sorting_asc:after,
table.dataTable thead .sorting_asc:before,
table.dataTable thead .sorting_asc_disabled:after,
table.dataTable thead .sorting_asc_disabled:before,
table.dataTable thead .sorting_desc:after,
table.dataTable thead .sorting_desc:before,
table.dataTable thead .sorting_desc_disabled:after,
table.dataTable thead .sorting_desc_disabled:before {
  bottom: .5em;
}
</style>
{% endblock extrastyle %}

{% block content %}

<div class="page-content-wrapper">
    <div class="page-content-wrapper-inner">
        <div class="viewport-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb has-arrow">
                    <li class="breadcrumb-item">
                        <a href="{% url 'seller:admin_view' %}">Dashboard</a>
                    </li>
                   
                    <li class="breadcrumb-item active" aria-current="page">Items</li>
                </ol>
            </nav>
        </div>


        <div class="content-viewport">
            <div class="row">
                <div class="col-lg-12">
                    <div class="grid">
                        <div class="grid-body">
                            <div class="item-wrapper">
                                <div class="table-responsive">
                                    <div id="json-sample-data-table_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                       
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <table id="dtBasicExample"
                                                    class="data-table table table-striped dataTable" role="grid"
                                                    aria-describedby="json-sample-data-table_info" style="width: 1088px;">
                                                
                                                    <thead>
                                                        <tr>
                                                            <th>Item</th>
                                                            <th>Quantity</th>
                                                            <th>Price</th>
                                                            <th>Discount Price</th>
                                                            <th>Category</th>
                                                            <th>Images</th>
                                                            <th>Update</th>
                                                            <th>Remove</th>
                                                        </tr>
                                                    </thead>
                                                    <tfoot>
                                                        <tr>
                                                            <th rowspan="1" colspan="1">Item</th>
                                                            <th rowspan="1" colspan="1">Quantity</th>
                                                            <th rowspan="1" colspan="1">price</th>
                                                            <th rowspan="1" colspan="1">Discount price</th>
                                                            <th rowspan="1" colspan="1">Category</th>
                                                            <th rowspan="1" colspan="1">Images</th>
                                                            <th rowspan="1" colspan="1">Update</th>
                                                            <th rowspan="1" colspan="1">Remove</th>
                                                        </tr>
                                                    </tfoot>
                                                    <tbody>
                                                        {% include 'admin-dash/partial_item_list.html' %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                      
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include "admin-dash/footer.html" %}
</div>    

{% endblock content %}

{% block javascript %}
<script type="text/javascript">
  $(document).ready(function () {
        $('#dtBasicExample').DataTable();
        $('.dataTables_length').addClass('bs-select');
    });
</script>

{% endblock javascript %}

templates/admin-dash/navbar.html
 {% load static %}
    <nav class="t-header">
      {% if messages %}
      {% for message in messages %}
      
      <script type=text/javascript>
      
                                toastr["{{ message.tags }}"]("{{ message }}",toastr.options={
                          "closeButton": false,
                          "debug": false,
                          "newestOnTop": true,
                          "progressBar": false,
                          "positionClass": "md-toast-top-full-width",
                          "preventDuplicates": true,
                          "onclick": null,
                          "showDuration": 7000,
                          "hideDuration": 3000,
                          "timeOut": 5000,
                          "extendedTimeOut": 1000,
                          "showEasing": "swing",
                          "hideEasing": "linear",
                          "showMethod": "slideDown",
                          "hideMethod": "slideUp"
                          })
                </script>
      {% endfor %}
      {% endif %}
      <div class="t-header-brand-wrapper">
        <a href="index.html">
          <img class="logo" src="{% static 'assets/images/logo.svg' %}" alt="">
          <img class="logo-mini" src="{% static 'assets/images/logo_mini.svg' %}" alt="">
        </a>
      </div>
      <div class="t-header-content-wrapper">
        <div class="t-header-content">
          <button class="t-header-toggler t-header-mobile-toggler d-block d-lg-none">
            <i class="mdi mdi-menu"></i>
          </button>
          <form action="#" class="t-header-search-box">
            <div class="input-group">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Search" autocomplete="off">
              <button class="btn btn-primary" type="submit"><i class="mdi mdi-arrow-right-thick"></i></button>
            </div>
          </form>
        
          <ul class="nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" id="notificationDropdown" data-toggle="dropdown" aria-expanded="false">
                <i class="mdi mdi-bell-outline mdi-1x"></i>
              </a>
              <div class="dropdown-menu navbar-dropdown dropdown-menu-right" aria-labelledby="notificationDropdown">
                <div class="dropdown-header">
                  <h6 class="dropdown-title">Notifications</h6>
                  <p class="dropdown-title-text">You have 4 unread notification</p>
                </div>
                <div class="dropdown-body">
                  <div class="dropdown-list">
                    <div class="icon-wrapper rounded-circle bg-inverse-primary text-primary">
                      <i class="mdi mdi-alert"></i>
                    </div>
                    <div class="content-wrapper">
                      <small class="name">Storage Full</small>
                      <small class="content-text">Server storage almost full</small>
                    </div>
                  </div>
                  <div class="dropdown-list">
                    <div class="icon-wrapper rounded-circle bg-inverse-success text-success">
                      <i class="mdi mdi-cloud-upload"></i>
                    </div>
                    <div class="content-wrapper">
                      <small class="name">Upload Completed</small>
                      <small class="content-text">3 Files uploded successfully</small>
                    </div>
                  </div>
                  <div class="dropdown-list">
                    <div class="icon-wrapper rounded-circle bg-inverse-warning text-warning">
                      <i class="mdi mdi-security"></i>
                    </div>
                    <div class="content-wrapper">
                      <small class="name">Authentication Required</small>
                      <small class="content-text">Please verify your password to continue using cloud services</small>
                    </div>
                  </div>
                </div>
                <div class="dropdown-footer">
                  <a href="#">View All</a>
                </div>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" id="messageDropdown" data-toggle="dropdown" aria-expanded="false">
                <i class="mdi mdi-message-outline mdi-1x"></i>
                <span class="notification-indicator notification-indicator-primary notification-indicator-ripple"></span>
              </a>
              <div class="dropdown-menu navbar-dropdown dropdown-menu-right" aria-labelledby="messageDropdown">
                <div class="dropdown-header">
                  <h6 class="dropdown-title">Messages</h6>
                  <p class="dropdown-title-text">You have 4 unread messages</p>
                </div>
                <div class="dropdown-body">
                  <div class="dropdown-list">
                    <div class="image-wrapper">
                      <img class="profile-img" src="{% static 'assets/images/profile/male/image_1.png' %}" alt="profile image">
                      <div class="status-indicator rounded-indicator bg-success"></div>
                    </div>
                    <div class="content-wrapper">
                      <small class="name">Clifford Gordon</small>
                      <small class="content-text">Lorem ipsum dolor sit amet.</small>
                    </div>
                  </div>
                  <div class="dropdown-list">
                    <div class="image-wrapper">
                      <img class="profile-img" src="{% static 'assets/images/profile/female/image_2.png' %}" alt="profile image">
                      <div class="status-indicator rounded-indicator bg-success"></div>
                    </div>
                    <div class="content-wrapper">
                      <small class="name">Rachel Doyle</small>
                      <small class="content-text">Lorem ipsum dolor sit amet.</small>
                    </div>
                  </div>
                  <div class="dropdown-list">
                    <div class="image-wrapper">
                      <img class="profile-img" src="{% static 'assets/images/profile/male/image_3.png' %}" alt="profile image">
                      <div class="status-indicator rounded-indicator bg-warning"></div>
                    </div>
                    <div class="content-wrapper">
                      <small class="name">Lewis Guzman</small>
                      <small class="content-text">Lorem ipsum dolor sit amet.</small>
                    </div>
                  </div>
                </div>
                <div class="dropdown-footer">
                  <a href="#">View All</a>
                </div>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" id="appsDropdown" data-toggle="dropdown" aria-expanded="false">
                <i class="mdi mdi-apps mdi-1x"></i>
              </a>
              <div class="dropdown-menu navbar-dropdown dropdown-menu-right" aria-labelledby="appsDropdown">
                <div class="dropdown-header">
                  <h6 class="dropdown-title">Apps</h6>
                  <p class="dropdown-title-text mt-2">Authentication required for 3 apps</p>
                </div>
                <div class="dropdown-body border-top pt-0">
                  <a class="dropdown-grid">
                    <i class="grid-icon mdi mdi-jira mdi-2x"></i>
                    <span class="grid-tittle">Jira</span>
                  </a>
                  <a class="dropdown-grid">
                    <i class="grid-icon mdi mdi-trello mdi-2x"></i>
                    <span class="grid-tittle">Trello</span>
                  </a>
                  <a class="dropdown-grid">
                    <i class="grid-icon mdi mdi-artstation mdi-2x"></i>
                    <span class="grid-tittle">Artstation</span>
                  </a>
                  <a class="dropdown-grid">
                    <i class="grid-icon mdi mdi-bitbucket mdi-2x"></i>
                    <span class="grid-tittle">Bitbucket</span>
                  </a>
                </div>
                <div class="dropdown-footer">
                  <a href="#">View All</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

templates/admin-dash/order_list.html
{% load static %}
{% for order in orders %}
    <tr>
      <td class="pr-0 pl-4">
        <img class="profile-img img-sm" src="{% static 'assets/images/profile/male/image_4.png' %}" alt="profile image">
      </td>
      <td class="pl-md-0">
        <small class="text-black font-weight-medium d-block">{{order.user.first_name}} {{order.user.last_name}}</small>
        <span class="text-gray">
          <span class="status-indicator rounded-indicator small bg-primary"></span>Account Deactivated </span>
      </td>
      <td>
        {% for order in order.items.all %}
          {{ order.item.title }}<br>
        {% endfor %}
      </td>
      <td>
        {% for order in order.items.all %}
            {{ order.quantity }}<br>
        {% endfor %}
      </td>
      <td>
        <small>{{order.ref_code}}</small>
      </td>
      <td>{{order.ordered_date}}</td>

    </tr>
    {% empty %}
    <tr>
      <td colspan="6" class="text-center bg-warning">No orders yet</td>
    </tr>
{% endfor %}

templates/admin-dash/partial_item_create.html
<form method="post" action="{%  url 'seller:add_item' %}" class="js-item-create-form">
  {% csrf_token %}

  <div class="modal-header">

    <h4 class="modal-title">Create a new item</h4>

     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

  </div>

  <div class="modal-body">
    {% include 'admin-dash/partial_item_form.html' %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Create item</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>

</form>

templates/admin-dash/partial_item_delete.html
<form method="post" action="{% url 'seller:delete_item' item.slug %}" class="js-item-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm item deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the item <strong>{{ item.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete item</button>
  </div>
</form>

templates/admin-dash/partial_item_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% render_field field class="form-control" %}
      {% for error in field.errors %}
        <p class="help-block">{{ error }}</p>
      {% endfor %}
  </div>
{% endfor %}

<!-- {{ formset.management_form }}-->
<!--{% for form in formset %}-->
<!--  {% for field in form %}-->
<!--    {{ field }}-->
<!--  {% endfor %}-->
<!--{% endfor %}-->

templates/admin-dash/partial_item_list.html
{% for item in items %}

    <tr>
        <td>{{item.title}}</td>
        <td>{{item.quantity}}</td>
        <td>{{item.price}}</td>
        <td>{{item.discount_price}}</td>
        <td>
          {% for categor in item.category.all %}
              --{{ categor.name }}--
          {% endfor %}
        </td>
        <td>
            <button class="btn btn-outline-info btn-sm js-upload-photos"
                    data-url="{% url 'seller:basic_upload' %}"
                    type="button">
                    <i class="mdi mdi-collage"></i>
                          Add Images
            </button>
        </td>
        <td>
            <button type="button"
                    class="btn btn-warning btn-sm js-update-item"
                    data-url="{% url 'seller:update_item' item.slug %}">
                    <i class="mdi mdi-border-color"></i>
                    Update
            </button>
        </td>
        <td>
            <button type="button"
                    class="btn btn-danger btn-sm js-delete-item"
                    data-url="{% url 'seller:delete_item' item.slug %}">
                <i class="mdi mdi-delete"></i>
                Delete
            </button>
        </td>
    </tr>

 {% empty %}
    <tr>
      <td colspan="7" class="text-center bg-warning">No items yet</td>
    </tr>

{% endfor %}

templates/admin-dash/partial_item_update.html
<form method="post" action="{% url 'seller:update_item' form.instance.slug %}" class="js-item-update-form">
  {% csrf_token %}

  <div class="modal-header">
    <h4 class="modal-title">Update item</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {% include 'admin-dash/partial_item_form.html' %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Update item</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</form>

templates/admin-dash/scripts.html
{% load static %}
<!-- SCRIPT LOADING START FORM HERE /////////////-->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/core.js' %}"></script>
    <script src="{% static 'assets/vendors/js/vendor.addons.js' %}"></script>

    <!-- MDBootstrap Datatables  -->
    <script type="text/javascript" src="{% static 'js/addons/datatables.js' %}"></script>
    
    <script src="{% static 'js/addons/datatables-select.js' %}"></script>


    <!-- endinject -->
    <!-- Vendor Js For This Page Ends-->
    <script src="{% static 'assets/vendors/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'assets/js/charts/chartjs.addon.js' %}"></script>
    <!-- Vendor Js For This Page Ends-->
    <!-- build:js -->
    <script src="{% static 'assets/js/template.js' %}"></script>
    <script src="{% static 'assets/js/dashboard.js' %}"></script>
    <!-- endbuild -->